### ISSUE TITLE
你好，非常感谢您的分享，请问从哪儿能下载到CDTB的数据集？期待您的回复

### ISSUE THREAD

**Issue by AlloyMei** [oisc/cdtparser#1]

**Comment by oisc** [comment]
你好：
请联系苏州大学孔芳教（kongfang@suda.edu.cn）

在 2019年11月20日，12:53，AlloyMei <notifications@github.com> 写道：

﻿

**Comment by oisc** [comment]
**Edit for privacy reason**

**Comment by AlloyMei** [comment]
好的，非常感谢您提供的信息！ @oisc
